<a href="https://colab.research.google.com/github/averma12/Kaggle/blob/master/Santander_Classification_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import io,os
import numpy as np
import pandas as pd

In [0]:
import json

In [0]:
kaggle_json = {"username":"averma12","key":"7884c1732361c94dd1db94795441bee6"}

In [0]:
os.makedirs('/content/.kaggle/',exist_ok=True)

In [0]:
os.makedirs('/root/.kaggle/',exist_ok=True)

In [0]:
with open('/content/.kaggle/kaggle.json', 'w') as file:
  json.dump(kaggle_json, file)

In [0]:
!cp /content/.kaggle/kaggle.json ~/.kaggle/kaggle.json

In [8]:
! kaggle competitions download -c santander-customer-satisfaction

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /root/.kaggle/kaggle.json'
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.6 / client 1.5.4)
Downloading sample_submission.csv.zip to /content
  0% 0.00/176k [00:00<?, ?B/s]
100% 176k/176k [00:00<00:00, 63.3MB/s]
Downloading test.csv.zip to /content
  0% 0.00/3.31M [00:00<?, ?B/s]
100% 3.31M/3.31M [00:00<00:00, 107MB/s]
Downloading train.csv.zip to /content
  0% 0.00/3.34M [00:00<?, ?B/s]
100% 3.34M/3.34M [00:00<00:00, 101MB/s]

In [14]:
! unzip /content/train.csv.zip

Archive:  /content/train.csv.zip
  inflating: train.csv

In [0]:
df = pd.read_csv('train.csv')

In [16]:
len(df)

76020

In [17]:
df.head()

   ID  var3  var15  ...  saldo_medio_var44_ult3          var38  TARGET
0   1     2     23  ...                     0.0   39205.170000       0
1   3     2     34  ...                     0.0   49278.030000       0
2   4     2     23  ...                     0.0   67333.770000       0
3   8     2     37  ...                     0.0   64007.970000       0
4  10     2     39  ...                     0.0  117310.979016       0

[5 rows x 371 columns]